stages:
  - test

php-70:
  stage: test
  image: debian:stretch
  before_script:
    - apt-get update && apt-get install php-cli composer -y
  script:
    - composer validate
    - composer install
    - composer test

php-73:
  stage: test
  image: debian:buster
  before_script:
    - apt-get update && apt-get install php-cli composer -y
  script:
    - composer validate
    - composer install
    - composer test
